# Command line arguments
cli_args:
  split: "training"
  tasks: ["28e73c20", "5c2c9af4", "6b9890af"]
  output_dir: "outputs/depth_experiment/layer8_model"
  device: "cuda:2"

# Model configuration
model:
  n_layers: 8
  share_up_dim: 16
  share_down_dim: 8
  decoding_dim: 4
  softmax_dim: 2
  cummax_dim: 4
  shift_dim: 4
  nonlinear_dim: 16

# Optimizer configuration
optimizer:
  lr: 0.01
  betas: [0.5, 0.9]

# Training configuration
training:
  n_iterations: 2500
  plot_interval: 50 






